use_frameworks!

platform :ios, '8.0'

target 'AbNSString_Example' do
  pod 'AbNSString', :path => '../'

  target 'AbNSString_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
